### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by andrewpbray** [ds-elections/rcv#2]
- [x] split tidy function into read, tidy, and code-to-character function
- [x] be sure your read/import function can use the example data set included in this package (add if statement for if the argument is a url/path or a dataframe. if the later, you can just return the dataframe and move on to the next step).
- [x] wrap up `rcv_tally()` and `characterize()`
- [x] add README
- [x] update Sankey (potentially from non-d3 function) and visually align with results dataframe
- [x] clean up directory structure
- [x] minimize package loading
- [x] get travis ci working
- [x] add ChoicePlus to cleaning functions
- [x] do some testing: restart blank r session, grab package from github, try running examples, reading help files, etc.

**Comment by jayleetx** [comment]
`characterize( )` is done, but due to some output formatting changes it doesn't work any more with `rcv_tally( )`. We'll work on that later/in the morning.

**Comment by andrewpbray** [comment]
great!
