### ISSUE TITLE
Goals/Todo

### ISSUE THREAD

**Issue by jayleetx** [ds-elections/rcv#4]
- [ ]  Get STV algorithm up and running
- [ ]  Code in specific rules for the cities we have data for
- [ ]  Start putting in parameters to play with: STV quota, option for double rankings, etc.
- [ ]  Tests tests tests
- [ ]  Shiny app for access?
